- update P0 to be silent when del/add upgraded services and to be   more robust and actually do something if it detects more than one   symlink
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@6514 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/releases/2.0-CURRENT/rpm-helper/SOURCES/rpm-helper-0.15-avx-srv.patch b/releases/2.0-CURRENT/rpm-helper/SOURCES/rpm-helper-0.15-avx-srv.patch
--- a/releases/2.0-CURRENT/rpm-helper/SOURCES/rpm-helper-0.15-avx-srv.patch
+++ b/releases/2.0-CURRENT/rpm-helper/SOURCES/rpm-helper-0.15-avx-srv.patch
@@ -117,8 +117,8 @@
 +
 +# del-srv ends here
 --- add-service.avx	2006-02-09 03:47:14.000000000 -0700
-+++ add-service	2006-10-21 13:13:24.000000000 -0600
-@@ -19,77 +19,26 @@
++++ add-service	2006-12-14 12:34:54.000000000 -0700
+@@ -19,77 +19,29 @@
  num=$2				# number of packages installed
  srv=$3				# name of the service
  
@@ -179,13 +179,17 @@
 +    set -- /etc/runlevels/default/*${srv}
      if [ $# -gt 1 ]; then
 -	echo 1>&2 "add-service: Error: $srv appears multiple times: $*"
-+	echo 1>&2 "add-service: Error: ${srv} appears multiple times: $*"
-     fi
+-    fi
 -    if [ -f "$1" ]; then
 -	/sbin/chkconfig --add $srv
-+    if [ -L "$1" ]; then
-+        /sbin/rc-update del ${srv} default
-+        /sbin/rc-update add ${srv} default
++	echo 1>&2 "add-service: Error: ${srv} appears multiple times: $*"
++	echo 1>&2 "add-service: Fixing previous errors"
++	# if we get here, we need to delete the multiples and re-add the service
++	rm -f $*
++	/sbin/rc-update add ${srv} default >/dev/null 2>&1 || :
++    elif [ -L "$1" ]; then
++        /sbin/rc-update del ${srv} default >/dev/null 2>&1 || :
++        /sbin/rc-update add ${srv} default >/dev/null 2>&1 || :
      fi
  
      # restart the service if already running
