- add /var/log/btmp by default - rediff P2 - sync with cooker 7.06-49mdk (only pertinent entries noted):   - network service: check actual value of MII_NOT_SUPPORTED instead of only     testing if the variable exists (tvignaud)   - add Han Boetes patch to set font on every text console, not only the     first one (tvignaud)   - rc.sysinit: added support for mdadm and lvm2 (bluca)   - rc.sysinit: fixed loading of st module (bluca)   - rc.local: option not to muck with /etc/issue (this is needed for sites     where policy, or law, enforce use of banners before login) (bluca)   - init.d/network: reload restarts active interfaces, restarts set boot     behaviour (bug #6112) (bluca)   - init.d/functions: fix print of multiple pid in status() (bug #6334)     (bluca)   - halt: added support for lvm2 (found by Navindra Umanee) (flepied)   - fix /sbin/setsysfont to work only on current console (Andrey Borzenkov)     (flepied)   - fix /sbin/setsysfont regarding compressed fonts (Luca Berra) (flepied)   - use fixed /sbin/setsysfont in rc (bug #6185) (Andrey Borzenkov)     (flepied)   - rc.d/rc.sysinit: no more depmod at boot (Nicolas) (flepied)   - move proc mounting after font initialization (warly)   - do not lock cdrom drive when mounted (warly)   - mandrake/usb: mount /proc/bus/usb as usbdevfs for all kernel 2.4/2.6     needed by speedtouch alcatel modem in user-mode/kernel-mode (Nicolas)     (flepied)   - rc.d/rc.sysinit: lookup device-mapper in /proc/misc too (bug #8398)     (flepied)   - call upsd earlier in halt script (warly) - NOTE: this package needs some serious cleaning and should likely be fully   branched away from the Mandrake patch (so a single OpenSLS-specific patch)
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@1608 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch b/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch
--- a/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch
+++ b/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch
@@ -1,53 +1,75 @@
---- sysctl.conf.opensls	2004-03-05 13:01:32.000000000 -0700
-+++ sysctl.conf	2004-03-05 13:01:33.000000000 -0700
+--- sysconfig.txt.opensls	2004-03-05 13:01:32.000000000 -0700
++++ sysconfig.txt	2004-03-05 13:01:33.000000000 -0700
+@@ -554,7 +554,7 @@
+       /sbin/pump
+       /sbin/dhcpxd
+   if you have a preferred client define the DHCP_CLIENT variable. 
+-  When you use dhclient (which it is the default on a Mandrake-Linux
++  When you use dhclient (which is the default on an OpenSLS
+   system) you can specify a timeout of waiting the answer from server,
+   the option is called DHCP_TIMEOUT the default is 60 sec.
+ 
+--- sysctl.conf.opensls	2004-05-11 09:15:15.000000000 -0600
++++ sysctl.conf	2004-05-11 09:18:19.000000000 -0600
 @@ -1,4 +1,4 @@
--# Kernel sysctl configuration file for Mandrake Linux
+-# Kernel sysctl configuration file for Mandrakelinux
 +# Kernel sysctl configuration file for OpenSLS
  #
  # For binary values, 0 is disabled, 1 is enabled.  See sysctl(8) and
  # sysctl.conf(5) for more details.
---- rc.d/rc.local.opensls	2004-03-05 13:01:33.000000000 -0700
-+++ rc.d/rc.local	2004-03-05 13:02:52.000000000 -0700
-@@ -10,8 +10,8 @@
+@@ -21,8 +21,3 @@
+ 
+ # on Andrey Borzenkov suggestion
+ dev.cdrom.autoclose=0
+-# removed to fix some digital extraction problems 
+-# dev.cdrom.check_media=1
+-
+-# to be able to eject via the device eject button (magicdev)
+-dev.cdrom.lock=0
+--- inittab.opensls	2004-05-11 09:15:15.000000000 -0600
++++ inittab	2004-05-11 09:19:22.000000000 -0600
+@@ -6,7 +6,7 @@
+ #               Modified for RHS Linux by Marc Ewing and Donnie Barnes
+ #
+ 
+-# Default runlevel. The runlevels used by Mandrakelinux are:
++# Default runlevel. The runlevels used by OpenSLS are:
+ #   0 - halt (Do NOT set initdefault to this)
+ #   1 - Single user mode
+ #   2 - Multiuser, without NFS (The same as 3, if you do not have networking)
+--- rc.d/rc.local.opensls	2004-05-11 09:15:17.000000000 -0600
++++ rc.d/rc.local	2004-05-11 09:22:28.000000000 -0600
+@@ -15,13 +15,13 @@
+     fi
+ fi
+ 
+-SYSTEM=${SYSTEM=Mandrakelinux}
++SYSTEM=${SYSTEM=OpenSLS}
+ 
  # Source functions
  . /etc/init.d/functions
  
--if [ -f /etc/mandrake-release -a $SECURE_LEVEL -lt 4 ]; then
+-if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/mandrake-release ]; then
 -    R=$(cat /etc/mandrake-release)
-+if [ -f /etc/opensls-release -a $SECURE_LEVEL -lt 4 ]; then
++if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/opensls-release ]; then
 +    R=$(cat /etc/opensls-release)
  
      arch=$(uname -m)
      a="a"
-@@ -49,8 +49,8 @@
- 	echo "$R" >> /etc/issue.net
- 	echo "Kernel $(uname -r) on $a $SMP$(uname -m)" >> /etc/issue.net
-     else	
--	echo "Welcome to Mandrake Linux" > /etc/issue.net
--	echo "-------------------------" >> /etc/issue.net
-+	echo "Welcome to OpenSLS" > /etc/issue.net
-+	echo "------------------" >> /etc/issue.net
-     fi
- elif [ $SECURE_LEVEL -ge 4 ]; then
-     rm -f /etc/issue /etc/issue.net
---- rc.d/rc.sysinit.opensls	2004-03-05 13:01:33.000000000 -0700
-+++ rc.d/rc.sysinit	2004-03-05 13:01:33.000000000 -0700
-@@ -97,11 +97,11 @@
+--- rc.d/rc.sysinit.opensls	2004-05-11 09:15:17.000000000 -0600
++++ rc.d/rc.sysinit	2004-05-11 09:23:51.000000000 -0600
+@@ -98,8 +98,8 @@
  # Print a banner. ;)
  # C-like escape sequences don't work as 2nd and up parameters of gprintf,
  # so real escap chars were written
 -PRODUCT=`sed "s/.*release \([0-9.]*\).*/\1/g" /etc/mandrake-release 2> /dev/null`
+-SYSTEM=${SYSTEM=Mandrakelinux}
 +PRODUCT=`sed "s/.*release \([0-9.]*\).*/\1/g" /etc/opensls-release 2> /dev/null`
++SYSTEM=${SYSTEM=OpenSLS}
  if [ "$BOOTUP" != "serial" ]; then
-- gprintf "\t\t\tWelcome to %sMandrake%s Linux %s" `echo -en "\\033[1;36m"` `echo -en "\\033[0;39m"` "$PRODUCT"
-+ gprintf "\t\t\tWelcome to %sOpenSLS%s %s" `echo -en "\\033[1;36m"` `echo -en "\\033[0;39m"` "$PRODUCT"
+  gprintf "\t\t\tWelcome to %s" "`echo -en '\\033[1;36m'`$SYSTEM`echo -en '\\033[0;39m'` $PRODUCT"
  else
-- gprintf "\t\t\tWelcome to %sMandrake%s Linux %s" "" "" "$PRODUCT"
-+ gprintf "\t\t\tWelcome to %sOpenSLS%s %s" "" "" "$PRODUCT"
- fi
- echo -en "\r"
- echo
-@@ -1093,13 +1093,13 @@
+@@ -1118,13 +1118,13 @@
  fi
  
  if [ -f /var/lock/TMP_1ST ];then
@@ -65,46 +87,45 @@
  fi
  
  # (pixel) a kind of profile for XF86Config
---- inittab.opensls	2004-03-05 13:01:32.000000000 -0700
-+++ inittab	2004-03-05 13:01:33.000000000 -0700
-@@ -6,7 +6,7 @@
- #               Modified for RHS Linux by Marc Ewing and Donnie Barnes
- #
+--- mandrake/mandrake_firstime.opensls	2004-05-11 09:15:15.000000000 -0600
++++ mandrake/mandrake_firstime	2004-05-11 09:24:57.000000000 -0600
+@@ -1,5 +1,5 @@
+ #!/bin/sh
+-# Description: Launch Mandrake Configuration for the first time.
++# Description: Launch OpenSLS Configuration for the first time.
+ # (c) MandrakeSoft, Chmouel Boudjnah <chmouel@mandrakesoft.com>
+ # 	$Id: mandrake_firstime,v 1.18 2003/09/04 14:10:01 tvignaud Exp $	
  
--# Default runlevel. The runlevels used by Mandrake Linux are:
-+# Default runlevel. The runlevels used by OpenSLS are:
- #   0 - halt (Do NOT set initdefault to this)
- #   1 - Single user mode
- #   2 - Multiuser, without NFS (The same as 3, if you do not have networking)
---- sysconfig.txt.opensls	2004-03-05 13:01:32.000000000 -0700
-+++ sysconfig.txt	2004-03-05 13:01:33.000000000 -0700
-@@ -554,7 +554,7 @@
-       /sbin/pump
-       /sbin/dhcpxd
-   if you have a preferred client define the DHCP_CLIENT variable. 
--  When you use dhclient (which it is the default on a Mandrake-Linux
-+  When you use dhclient (which is the default on an OpenSLS
-   system) you can specify a timeout of waiting the answer from server,
-   the option is called DHCP_TIMEOUT the default is 60 sec.
+@@ -11,16 +11,6 @@
+ # If fail erase the temporary file
+ trap 'rm -f /var/lock/TMP_1ST' 1 2 3 15
  
---- mandrake/mandrake_everytime.opensls	2004-03-05 13:01:32.000000000 -0700
-+++ mandrake/mandrake_everytime	2004-03-05 13:01:33.000000000 -0700
+-#Rebuild Mozilla registry
+-# be sure that mozilla registry is ok
+-for MOZ_REBUILD_DATABASE in /usr/lib*/mozilla-*/mozilla-rebuild-databases.pl; do
+-[ -x $MOZ_REBUILD_DATABASE ] &&
+-{
+- action "Building Mozilla registry" $MOZ_REBUILD_DATABASE 2>> $FLO
+-}
+-done
+-
+-
+ [ -s $FLO ] || rm -f $FLO
+ 
+ # Finish
+--- mandrake/mandrake_everytime.opensls	2004-05-11 09:15:15.000000000 -0600
++++ mandrake/mandrake_everytime	2004-05-11 09:26:01.000000000 -0600
 @@ -1,5 +1,5 @@
  #!/bin/bash
 -# Description: Launch diverses Mandrake Scripts on boot.
 +# Description: Launch diverses OpenSLS Scripts on boot.
  # (c) MandrakeSoft, Chmouel Boudjnah <chmouel@mandrakesoft.com>
- # 	$Id: mandrake_everytime,v 1.18 2003/07/04 12:22:40 flepied Exp $	
+ # 	$Id: mandrake_everytime,v 1.19 2003/07/11 21:02:33 flepied Exp $	
  
-@@ -7,20 +7,6 @@
+@@ -7,15 +7,6 @@
  
  [ -e /etc/sysconfig/system ] && . /etc/sysconfig/system
  
--# Build KdmSession
--[ -x /usr/sbin/fndSession ] && {
--       action "Building Window Manager Sessions" /usr/sbin/fndSession
--}
--
 -# Disabling supermount if not here
 -if [[ $(uname -m) != sparc*  ]];then
 -    if grep -q '^\/.*supermount.*' /etc/fstab && \
@@ -117,28 +138,3 @@
  # setup eth* (without configuring it) interfaces before the
  # hotplug/pcmcia started so we are sure that what we have configured
  # in /etc/modules.conf get the device we have affected.
---- mandrake/mandrake_firstime.opensls	2004-03-05 13:01:32.000000000 -0700
-+++ mandrake/mandrake_firstime	2004-03-05 13:01:33.000000000 -0700
-@@ -1,5 +1,5 @@
- #!/bin/sh
--# Description: Launch Mandrake Configuration for the first time.
-+# Description: Launch OpenSLS Configuration for the first time.
- # (c) MandrakeSoft, Chmouel Boudjnah <chmouel@mandrakesoft.com>
- # 	$Id: mandrake_firstime,v 1.17 2003/09/01 15:01:58 tvignaud Exp $	
- 
-@@ -11,15 +11,6 @@
- # If fail erase the temporary file
- trap 'rm -f /var/lock/TMP_1ST' 1 2 3 15
- 
--#Rebuild Mozilla registry
--# be sure that mozilla registry is ok
--MOZ_REBUILD_DATABASE="/usr/lib/mozilla-*/mozilla-rebuild-databases.pl"
--[ -x $MOZ_REBUILD_DATABASE ] &&
--{
-- action "Building Mozilla registry" $MOZ_REBUILD_DATABASE 2>> $FLO
--}
--
--
- [ -s $FLO ] || rm -f $FLO
- 
- # Finish
