- remove supermount - minor spec cleanups - remove ifplugd requirement - more OpenSLS branding - s/mandrake_{everytime,firstime,consmap}/opensls_{everytime,firstime,consmap}/
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@1217 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch b/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch
--- a/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch
+++ b/branches/CURRENT_1_0/packages/initscripts/initscripts-opensls.patch
@@ -1,5 +1,13 @@
---- initscripts-7.06/rc.d/rc.local.mdk	2003-11-23 08:16:50.000000000 -0700
-+++ initscripts-7.06/rc.d/rc.local	2003-11-23 08:17:38.000000000 -0700
+--- sysctl.conf.opensls	2004-03-05 13:01:32.000000000 -0700
++++ sysctl.conf	2004-03-05 13:01:33.000000000 -0700
+@@ -1,4 +1,4 @@
+-# Kernel sysctl configuration file for Mandrake Linux
++# Kernel sysctl configuration file for OpenSLS
+ #
+ # For binary values, 0 is disabled, 1 is enabled.  See sysctl(8) and
+ # sysctl.conf(5) for more details.
+--- rc.d/rc.local.opensls	2004-03-05 13:01:33.000000000 -0700
++++ rc.d/rc.local	2004-03-05 13:02:52.000000000 -0700
 @@ -10,8 +10,8 @@
  # Source functions
  . /etc/init.d/functions
@@ -11,7 +19,7 @@
  
      arch=$(uname -m)
      a="a"
-@@ -49,11 +49,12 @@
+@@ -49,8 +49,8 @@
  	echo "$R" >> /etc/issue.net
  	echo "Kernel $(uname -r) on $a $SMP$(uname -m)" >> /etc/issue.net
      else	
@@ -22,16 +30,14 @@
      fi
  elif [ $SECURE_LEVEL -ge 4 ]; then
      rm -f /etc/issue /etc/issue.net
- fi
- 
- touch /var/lock/subsys/local
-+u
-\ No newline at end of file
---- initscripts-7.06/rc.d/rc.sysinit.mdk	2003-11-23 08:18:42.000000000 -0700
-+++ initscripts-7.06/rc.d/rc.sysinit	2003-11-23 08:19:12.000000000 -0700
-@@ -99,9 +99,9 @@
+--- rc.d/rc.sysinit.opensls	2004-03-05 13:01:33.000000000 -0700
++++ rc.d/rc.sysinit	2004-03-05 13:01:33.000000000 -0700
+@@ -97,11 +97,11 @@
+ # Print a banner. ;)
+ # C-like escape sequences don't work as 2nd and up parameters of gprintf,
  # so real escap chars were written
- PRODUCT=`sed "s/.*release \([0-9.]*\).*/\1/g" /etc/mandrake-release 2> /dev/null`
+-PRODUCT=`sed "s/.*release \([0-9.]*\).*/\1/g" /etc/mandrake-release 2> /dev/null`
++PRODUCT=`sed "s/.*release \([0-9.]*\).*/\1/g" /etc/opensls-release 2> /dev/null`
  if [ "$BOOTUP" != "serial" ]; then
 - gprintf "\t\t\tWelcome to %sMandrake%s Linux %s" `echo -en "\\033[1;36m"` `echo -en "\\033[0;39m"` "$PRODUCT"
 + gprintf "\t\t\tWelcome to %sOpenSLS%s %s" `echo -en "\\033[1;36m"` `echo -en "\\033[0;39m"` "$PRODUCT"
@@ -41,11 +47,98 @@
  fi
  echo -en "\r"
  echo
---- initscripts-7.06/sysctl.conf.mdk	2003-11-23 08:19:54.000000000 -0700
-+++ initscripts-7.06/sysctl.conf	2003-11-23 08:19:54.000000000 -0700
-@@ -1,4 +1,4 @@
--# Kernel sysctl configuration file for Mandrake Linux
-+# Kernel sysctl configuration file for OpenSLS
+@@ -1093,13 +1093,13 @@
+ fi
+ 
+ if [ -f /var/lock/TMP_1ST ];then
+- if [ -f /etc/init.d/mandrake_firstime ];then
+-	/bin/sh /etc/init.d/mandrake_firstime
++ if [ -f /etc/init.d/opensls_firstime ];then
++	/bin/sh /etc/init.d/opensls_firstime
+  fi
+ fi
+ 
+-if [ -f /etc/init.d/mandrake_everytime ]; then 
+-	/bin/sh /etc/init.d/mandrake_everytime
++if [ -f /etc/init.d/opensls_everytime ]; then 
++	/bin/sh /etc/init.d/opensls_everytime
+ fi
+ 
+ # (pixel) a kind of profile for XF86Config
+--- inittab.opensls	2004-03-05 13:01:32.000000000 -0700
++++ inittab	2004-03-05 13:01:33.000000000 -0700
+@@ -6,7 +6,7 @@
+ #               Modified for RHS Linux by Marc Ewing and Donnie Barnes
  #
- # For binary values, 0 is disabled, 1 is enabled.  See sysctl(8) and
- # sysctl.conf(5) for more details.
+ 
+-# Default runlevel. The runlevels used by Mandrake Linux are:
++# Default runlevel. The runlevels used by OpenSLS are:
+ #   0 - halt (Do NOT set initdefault to this)
+ #   1 - Single user mode
+ #   2 - Multiuser, without NFS (The same as 3, if you do not have networking)
+--- sysconfig.txt.opensls	2004-03-05 13:01:32.000000000 -0700
++++ sysconfig.txt	2004-03-05 13:01:33.000000000 -0700
+@@ -554,7 +554,7 @@
+       /sbin/pump
+       /sbin/dhcpxd
+   if you have a preferred client define the DHCP_CLIENT variable. 
+-  When you use dhclient (which it is the default on a Mandrake-Linux
++  When you use dhclient (which is the default on an OpenSLS
+   system) you can specify a timeout of waiting the answer from server,
+   the option is called DHCP_TIMEOUT the default is 60 sec.
+ 
+--- mandrake/mandrake_everytime.opensls	2004-03-05 13:01:32.000000000 -0700
++++ mandrake/mandrake_everytime	2004-03-05 13:01:33.000000000 -0700
+@@ -1,5 +1,5 @@
+ #!/bin/bash
+-# Description: Launch diverses Mandrake Scripts on boot.
++# Description: Launch diverses OpenSLS Scripts on boot.
+ # (c) MandrakeSoft, Chmouel Boudjnah <chmouel@mandrakesoft.com>
+ # 	$Id: mandrake_everytime,v 1.18 2003/07/04 12:22:40 flepied Exp $	
+ 
+@@ -7,20 +7,6 @@
+ 
+ [ -e /etc/sysconfig/system ] && . /etc/sysconfig/system
+ 
+-# Build KdmSession
+-[ -x /usr/sbin/fndSession ] && {
+-       action "Building Window Manager Sessions" /usr/sbin/fndSession
+-}
+-
+-# Disabling supermount if not here
+-if [[ $(uname -m) != sparc*  ]];then
+-    if grep -q '^\/.*supermount.*' /etc/fstab && \
+-	! grep -q '[[:space:]]supermount$' /proc/filesystems  && \
+-	! modprobe -n supermount >/dev/null 2>/dev/null && [ -x /usr/bin/perl ];then
+-	action "Disabling Supermount" /usr/sbin/supermount -i disable
+-    fi
+-fi
+-
+ # setup eth* (without configuring it) interfaces before the
+ # hotplug/pcmcia started so we are sure that what we have configured
+ # in /etc/modules.conf get the device we have affected.
+--- mandrake/mandrake_firstime.opensls	2004-03-05 13:01:32.000000000 -0700
++++ mandrake/mandrake_firstime	2004-03-05 13:01:33.000000000 -0700
+@@ -1,5 +1,5 @@
+ #!/bin/sh
+-# Description: Launch Mandrake Configuration for the first time.
++# Description: Launch OpenSLS Configuration for the first time.
+ # (c) MandrakeSoft, Chmouel Boudjnah <chmouel@mandrakesoft.com>
+ # 	$Id: mandrake_firstime,v 1.17 2003/09/01 15:01:58 tvignaud Exp $	
+ 
+@@ -11,15 +11,6 @@
+ # If fail erase the temporary file
+ trap 'rm -f /var/lock/TMP_1ST' 1 2 3 15
+ 
+-#Rebuild Mozilla registry
+-# be sure that mozilla registry is ok
+-MOZ_REBUILD_DATABASE="/usr/lib/mozilla-*/mozilla-rebuild-databases.pl"
+-[ -x $MOZ_REBUILD_DATABASE ] &&
+-{
+- action "Building Mozilla registry" $MOZ_REBUILD_DATABASE 2>> $FLO
+-}
+-
+-
+ [ -s $FLO ] || rm -f $FLO
+ 
+ # Finish
