- 1.0.10 - enable all the stuff we couldn't use before without a 2.6 kernel (gssapi,   kerberos, nfsv4) - use the ./depends directory and let srv handle dependencies - add /var/lib/nfs/v4recovery - write run scripts for rpc.idmapd, rpc.gssd, and rpc.svcgssd and rework   the other runscripts - add a finish script for rpc.statd - try to sanely handle dependencies - NOTE: i'm comitting this but have no idea how well it will work.. the changeset   will already be huge so it'll be easier to work from the comitted version
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@6519 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/releases/2.0-CURRENT/nfs-utils/SOURCES/rpcsvcgssd.init b/releases/2.0-CURRENT/nfs-utils/SOURCES/rpcsvcgssd.init
--- a/releases/2.0-CURRENT/nfs-utils/SOURCES/rpcsvcgssd.init
+++ b/releases/2.0-CURRENT/nfs-utils/SOURCES/rpcsvcgssd.init
@@ -7,6 +7,16 @@
 # chkconfig: 345 19 69
 # description: Starts user-level daemon that manages RPCSEC GSS contexts \
 #	       for the NFSv4 server.
+#
+### BEGIN INIT INFO
+# Provides: rpcsvcgssd
+# Required-Start: $network
+# Required-Stop: $network
+# Default-Start: 3 4 5
+# Short-Description: RPCSEC GSS daemon
+# Description: Starts user-level daemon that manages RPCSEC GSS contexts
+#	       for the NFSv4 server.
+### END INIT INFO
 
 # Source function library.
 . /etc/init.d/functions
@@ -64,6 +74,20 @@ case "$1" in
 		echo "Error: RPC MTAB does not exist."
 		exit 1
 	}	
+
+	# don't try to start if the config file is missing
+	if ! [ -f /etc/krb5.keytab ]; then
+	    echo "Error: /etc/krb5.keytab does not exist."
+	    exit 1
+	fi
+
+	# don't try to start if nfs is not setup in kerberos
+	if [ -f /etc/krb5.keytab ]; then
+	    if [ -z `echo -e "rkt /etc/krb5.keytab\nl" | ktutil | awk '{ print $3}' | grep "^nfs\/"` ]; then
+		echo "No nfs key detected in default keytab, aborting."
+		exit 1
+	    fi
+	fi
 
 	# Start daemon.
 	daemon $prog ${OPTIONS}
