- 2.0.54 - the great apache2->httpd/httpd2->http migration - sync patches with mandrake 2.0.54-10mdk - use modules.d to load modules rather than modules.d - P122: security fix for CAN-2005-1268 - P123: security fix for CAN-2005-2088 - added README.urpmi - mod_userdir is it's own sub-package - BuildRequires: zlib-devel
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@4115 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/branches/CURRENT_1_1/packages/httpd/httpd-2.0.40-apctl.patch b/branches/CURRENT_1_1/packages/httpd/httpd-2.0.40-apctl.patch
--- a/branches/CURRENT_1_1/packages/httpd/httpd-2.0.40-apctl.patch
+++ b/branches/CURRENT_1_1/packages/httpd/httpd-2.0.40-apctl.patch
@@ -2,9 +2,15 @@
 - fail gracefully if a 1.3 config file is found
 - use links not lynx, and fail gracefully when neither is found
 - source sysconfig/httpd for custom env. vars etc.
+- make httpd -t work even in SELinux
+- refuse to restart into a bad config (done better on HEAD)
 
---- httpd-2.0.49/support/apachectl.in.apctl
-+++ httpd-2.0.49/support/apachectl.in
+Upstream-HEAD: vendor
+Upstream-2.0: vendor
+Upstream-Status: Vendor-specific changes for better initscript integration
+
+--- httpd-2.0.52/support/apachectl.in.apctl
++++ httpd-2.0.52/support/apachectl.in
 @@ -41,32 +41,27 @@
  # 
  # the path to your httpd binary, including options if necessary
@@ -51,7 +57,7 @@
  fi
  
  ERROR=0
-@@ -74,12 +69,33 @@
+@@ -74,23 +69,65 @@
      ARGV="-h"
  fi
  
@@ -74,8 +80,29 @@
 +fi
 +}
 +
++function testconfig() {
++# httpd is denied terminal access in SELinux, so run in the
++# current context to get stdout from $HTTPD -t.
++if test -x /usr/sbin/selinuxenabled && /usr/sbin/selinuxenabled; then
++  runcon -- `id -Z` $HTTPD -t
++else
++  $HTTPD -t
++fi
++ERROR=$?
++}
++
  case $ARGV in
- start|stop|restart|graceful)
+-start|stop|restart|graceful)
++restart|graceful)
++    if $HTTPD -t >&/dev/null; then
++       $HTTPD -k $ARGV
++       ERROR=$?
++    else
++       echo "apachectl: Configuration syntax error, will not run \"$ARGV\":"
++       testconfig
++    fi
++    ;;
++start|stop)
 +    check13
      $HTTPD -k $ARGV
      ERROR=$?
@@ -85,8 +112,10 @@
      $HTTPD -k start -DSSL
      ERROR=$?
      ;;
-@@ -88,9 +104,11 @@
-     ERROR=$?
+ configtest)
+-    $HTTPD -t
+-    ERROR=$?
++    testconfig
      ;;
  status)
 +    checklynx
