- mark /etc/rc.d/rc.local and /etc/rc.local as %config(noreplace) - compress the ChangeLog - remove the X11 config files - /sbin/netreport and /usr/sbin/usernetctl are not s
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@4317 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/branches/CURRENT_1_1/packages/initscripts/initscripts-7.61.1-avx-annvix.patch b/branches/CURRENT_1_1/packages/initscripts/initscripts-7.61.1-avx-annvix.patch
--- a/branches/CURRENT_1_1/packages/initscripts/initscripts-7.61.1-avx-annvix.patch
+++ b/branches/CURRENT_1_1/packages/initscripts/initscripts-7.61.1-avx-annvix.patch
@@ -3,9 +3,17 @@
 @@ -0,0 +1,2 @@
 +REWRITEISSUE=rewrite
 +REWRITEISSUENET=rewrite
---- Makefile.annvix	2005-02-28 15:42:51.000000000 -0700
-+++ Makefile	2005-02-28 15:42:51.000000000 -0700
-@@ -35,6 +35,7 @@
+--- Makefile.avx	2005-09-11 17:27:42.000000000 -0400
++++ Makefile	2005-09-11 17:28:42.000000000 -0400
+@@ -27,14 +27,13 @@
+ 	  install -m644 sysctl.conf.sparc $(ROOT)/etc/sysctl.conf ; fi
+ 	if uname -m | grep -q s390 ; then \
+ 	  install -m644 sysctl.conf.s390 $(ROOT)/etc/sysctl.conf ; fi
+-	mkdir -p $(ROOT)/etc/X11
+-	install -m755 prefdm $(ROOT)/etc/X11/prefdm
+ 	mkdir -p $(ROOT)/etc/sysconfig
+ 	mkdir -p $(ROOT)/etc/sysconfig/console
+ 	mkdir -p $(ROOT)/etc/sysconfig/console/consolefonts
  	mkdir -p $(ROOT)/etc/sysconfig/console/consoletrans
  	install -m644 sysconfig/init $(ROOT)/etc/sysconfig/init
  	install -m644 sysconfig/rawdevices $(ROOT)/etc/sysconfig/rawdevices
@@ -197,8 +205,73 @@
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    echo -n "]"
    echo -ne "\r"
---- rc.d/rc.sysinit.annvix	2005-03-01 13:02:02.000000000 -0700
-+++ rc.d/rc.sysinit	2005-03-01 13:11:15.000000000 -0700
+--- rc.d/rc.local.annvix	2005-02-28 15:42:51.000000000 -0700
++++ rc.d/rc.local	2005-02-28 15:48:06.000000000 -0700
+@@ -5,23 +5,15 @@
+ # want to do the full Sys V style init stuff.
+ 
+ [ -f /etc/sysconfig/system ] && source /etc/sysconfig/system
+-[ -f /etc/sysconfig/msec ] && source /etc/sysconfig/msec
+-[ -z "$SECURE_LEVEL" ] && SECURE_LEVEL=3
+ [ -f /etc/sysconfig/init ] && source /etc/sysconfig/init
+-if [ $SECURE_LEVEL -lt 4 ]; then
+-    [ -z "$REWRITEISSUE" ] && REWRITEISSUE=rewrite
+-    if [ $SECURE_LEVEL -lt 3 ]; then
+-	[ -z "$REWRITEISSUENET" ] && REWRITEISSUENET=rewrite
+-    fi
+-fi
+ 
+-SYSTEM=${SYSTEM=Mandrakelinux}
++SYSTEM=${SYSTEM=Annvix}
+ 
+ # Source functions
+ . /etc/init.d/functions
+ 
+-if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/mandrake-release ]; then
+-    R=$(cat /etc/mandrake-release)
++if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/annvix-release ]; then
++    R=$(cat /etc/annvix-release)
+ 
+     arch=$(uname -m)
+     a="a"
+@@ -45,12 +37,7 @@
+     # This will overwrite /etc/issue at every boot.  So, make any changes you
+     # want to make to /etc/issue here or you will lose them when you reboot.
+ 
+-    if [ -x /usr/bin/linux_logo ]; then
+-	/usr/bin/linux_logo -n -f | sed -e 's|\\|\\\\|g' > /etc/issue
+-	echo "" >> /etc/issue
+-    else
+-	> /etc/issue
+-    fi
++    > /etc/issue
+     echo "$R" >> /etc/issue
+     echo "Kernel $(uname -r) on $a $SMP$(uname -m) / \l" >> /etc/issue
+     
+@@ -63,21 +50,6 @@
+ 	gprintf "Welcome to %s\n" "$NAME" > /etc/issue.net
+ 	echo "-------------------------" >> /etc/issue.net
+     fi
+-else
+-    if [ -f /etc/security/msec/issue.$SECURE_LEVEL ]; then
+-	cat /etc/security/msec/issue.$SECURE_LEVEL > /etc/issue
+-    elif [ -f /etc/security/msec/issue ]; then
+-	cat /etc/security/msec/issue > /etc/issue
+-    else
+-	rm -f /etc/issue
+-    fi
+-    if [ -f /etc/security/msec/issue.net.$SECURE_LEVEL ]; then
+-	cat /etc/security/msec/issue.net.$SECURE_LEVEL > /etc/issue.net
+-    elif [ -f /etc/security/msec/issue.net ]; then
+-	cat /etc/security/msec/issue.net > /etc/issue.net
+-    else
+-	rm -f /etc/issue.net
+-    fi
+ fi
+ 
+ touch /var/lock/subsys/local
+--- rc.d/rc.sysinit.avx	2005-09-11 17:27:43.000000000 -0400
++++ rc.d/rc.sysinit	2005-09-11 17:50:06.000000000 -0400
 @@ -136,25 +136,6 @@
     /sbin/blockdev --flushbufs /dev/ram0 >/dev/null 2>&1
  fi
@@ -304,7 +377,15 @@
  
  # MiB: Device-Mapper initialization
  if [ -f /etc/evms.conf -a -x /sbin/evms_activate ] || [ -f /etc/lvm/lvm.conf -a -x /sbin/lvm2 ]; then
-@@ -570,13 +521,6 @@
+@@ -542,7 +493,6 @@
+ 	    _vgcmd_2="/sbin/lvm2 vgmknodes"
+ 	fi
+ 	_vgcmd_1="/sbin/lvm2 vgchange -a y"
+-	[ -n "$SELINUX" ] && restorecon /dev/mapper/control >/dev/null 2>&1
+     fi
+ fi
+ 
+@@ -570,13 +520,6 @@
      action $"Setting up Logical Volume Management:" ${_vgcmd_1} && ${_vgcmd_2}
  fi
  
@@ -318,7 +399,28 @@
  # Start up swapping. #we don't do encryted swap now since
  # (pixel) it was done between setting keytable and setting hostname
  #         but it can't be done before "vgchange -a y", 
-@@ -656,13 +600,13 @@
+@@ -635,34 +578,16 @@
+ # the preferred link.
+ rm -f /lib/modules/preferred /lib/modules/default
+ 
+-# tweak isapnp settings if needed.
+-if [ -n "$PNP" -a  -f /proc/isapnp -a -x /sbin/sndconfig ]; then
+-    /sbin/sndconfig --mungepnp >/dev/null 2>&1
+-fi
+-
+-# Load sound modules if and only if they need persistent DMA buffers
+-if LC_ALL=C /sbin/modprobe -c | grep -q "^[^#]*options[[:space:]]\+sound[[:space:]].*dmabuf=1" 2>/dev/null ; then
+-  RETURN=0
+-  alias=`/sbin/modprobe -c | awk '/^alias sound / { print $3 }'`
+-  if [ -n "$alias" -a "$alias" != "off" ]; then
+-      action $"Loading sound module ($alias): " modprobe sound
+-  fi
+-  alias=`/sbin/modprobe -c | awk '/^alias[[:space:]]+sound-slot-0[[:space:]]/ { print $3 }'`
+-  if [ -n "$alias" -a "$alias" != "off" ]; then
+-      action $"Loading sound module ($alias): " modprobe sound-slot-0
+-  fi
+-fi
+-
  if [ -f /proc/sys/kernel/modprobe ]; then
     if [ -n "$USEMODULES" ]; then
         sysctl -n -w kernel.modprobe="/sbin/modprobe" >/dev/null 2>&1
@@ -336,15 +438,188 @@
     fi
  fi
  
-@@ -753,7 +697,6 @@
- 
-  		str=$"(RAID Repair)"
- 		PS1="$str \# # "; export PS1
+@@ -674,8 +599,6 @@
+ # Add raid devices
+ if grep -q -s '^[[:space:]]*ARRAY[[:space:]]' /etc/mdadm.conf && [ -x /sbin/mdadm ]; then
+ 	raid=mdadm
+-elif grep -q -s '^[[:space:]]*raiddev[[:space:]]' /etc/raidtab; then
+-	raid=raidtools
+ fi
+ # Add raid devices
+ [ -n "${raid}" -a ! -f /proc/mdstat ] && modprobe md >/dev/null 2>&1
+@@ -691,77 +614,6 @@
+ 	else
+ 		echo OK
+ 	fi
+-		
+-elif [ "${raid}" = "raidtools" -a -f /proc/mdstat ]; then
+-	echo -n $"Starting up RAID devices: " 
+-
+-	rc=0
+-	
+-	for i in `awk '{if ($1=="raiddev") print $2}' /etc/raidtab`
+-	do
+-		RAIDDEV=`basename $i`
+-                RAIDSTAT=`LC_ALL=C grep "^$RAIDDEV : active" /proc/mdstat`
+-		if [ -z "$RAIDSTAT" ]; then
+-			# First scan the /etc/fstab for the "noauto"-flag
+-			# for this device. If found, skip the initialization
+-			# for it to avoid dropping to a shell on errors.
+-			# If not, try raidstart...if that fails then
+-			# fall back to raidadd, raidrun.  If that
+-			# also fails, then we drop to a shell
+-			RESULT=1
+-			INFSTAB=`LC_ALL=C grep -c "^$i" /etc/fstab`
+-			if [ $INFSTAB -eq 0 ] ; then
+-			    RESULT=0
+-			    RAIDDEV="$RAIDDEV(skipped)"
+-			fi
+-			NOAUTO=`LC_ALL=C grep "^$i" /etc/fstab | LC_ALL=C fgrep -c "noauto"`
+-			if [ $NOAUTO -gt 0 ]; then
+-			    RESULT=0
+-			    RAIDDEV="$RAIDDEV(skipped)"
+-			fi
+-			if [ $RESULT -gt 0 -a -x /sbin/raidstart ]; then
+-				/sbin/raidstart $i
+-				RESULT=$?
+-			fi
+-			if [ $RESULT -gt 0 -a -x /sbin/raid0run ]; then
+-				/sbin/raid0run $i
+-				RESULT=$?
+-			fi
+-			if [ $RESULT -gt 0 -a -x /sbin/raidadd -a -x /sbin/raidrun ]; then
+-				/sbin/raidadd $i
+-				/sbin/raidrun $i
+-				RESULT=$?
+-			fi
+-			if [ $RESULT -gt 0 ]; then
+-				rc=1
+-			fi
+-			echo -n "$RAIDDEV "
+-		else
+-			echo -n "$RAIDDEV "
+-		fi
+-	done
+-	echo
+-
+-	# A non-zero return means there were problems.
+-	if [ $rc -gt 0 ]; then
+-		local str=
+-		echo
+-		echo
+-		gprintf "*** An error occurred during the RAID startup\n"
+-		gprintf "*** Dropping you to a shell; the system will reboot\n"
+-		gprintf "*** when you leave the shell.\n"
+-
+- 		str=$"(RAID Repair)"
+-		PS1="$str \# # "; export PS1
 -		[ "$SELINUX" = "1" ] && disable_selinux
- 		sulogin
+-		sulogin
+-
+-            gprintf "Unmounting file systems\n"
+-	    umount -a
+-	    mount -n -o remount,ro /
+-            gprintf "Automatic reboot in progress.\n"
+-	    reboot -f
+-	fi
+ fi
  
-             gprintf "Unmounting file systems\n"
-@@ -1261,21 +1204,11 @@
+ # LVM initialization, take 2 (it could be on top of RAID)
+@@ -926,51 +778,6 @@
+ dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=512 2>/dev/null
+ 
+ 
+-# Configure machine if necessary.
+-if [ -f /.unconfigured ]; then
+-    if [ -x /usr/bin/rhgb-client ] && /usr/bin/rhgb-client --ping ; then
+-	chvt 1
+-    fi
+-
+-    if [ -x /usr/sbin/kbdconfig ]; then
+-	/usr/sbin/kbdconfig
+-    fi
+-    if [ -x /usr/bin/passwd ]; then 
+-        /usr/bin/passwd root
+-    fi
+-    if [ -x /usr/sbin/netconfig ]; then
+-	/usr/sbin/netconfig
+-    fi
+-    if [ -x /usr/sbin/timeconfig ]; then
+-	/usr/sbin/timeconfig
+-    fi
+-    if [ -x /usr/sbin/authconfig ]; then
+-	/usr/sbin/authconfig --nostart
+-    fi
+-    if [ -x /usr/sbin/ntsysv ]; then
+-	/usr/sbin/ntsysv --level 35
+-    fi
+-
+-    # Reread in network configuration data.
+-    if [ -f /etc/sysconfig/network ]; then
+-	. /etc/sysconfig/network
+-
+-	# Reset the hostname.
+-	action "Resetting hostname %s: " ${HOSTNAME} hostname ${HOSTNAME}
+-
+-	# Reset the NIS domain name.
+-	if [ -n "$NISDOMAIN" ]; then
+-	    action "Resetting NIS domain name %s: " $NISDOMAIN nisdomainname $NISDOMAIN
+-	fi
+-    fi
+-
+-    rm -f /.unconfigured
+-
+-    if [ -x /usr/bin/rhgb-client ] && /usr/bin/rhgb-client --ping ; then
+-	chvt 8
+-    fi
+-fi
+-
+ if [ -x /sbin/quotaon ]; then
+     action "Turning on user and group quotas for local filesystems: " /sbin/quotaon -aug
+ fi
+@@ -1018,40 +825,11 @@
+ fi
+ 
+ # Clean up various /tmp bits
+-rm -f /tmp/.X*-lock /tmp/.lock.* /tmp/.gdm_socket /tmp/.s.PGSQL.*
+-rm -rf /tmp/.X*-unix /tmp/.ICE-unix /tmp/.font-unix /tmp/hsperfdata_* \
+-       /tmp/kde-* /tmp/ksocket-* /tmp/mc-* /tmp/mcop-* /tmp/orbit-*  \
+-       /tmp/scrollkeeper-*  /tmp/ssh-*
+-# Make ICE directory
+-mkdir -m 1777 -p /tmp/.ICE-unix >/dev/null 2>&1
+-chown root:root /tmp/.ICE-unix
+-[ -n "$SELINUX" ] && restorecon /tmp/.ICE-unix >/dev/null 2>&1
+-
+-# Delete VNC & X locks
+-rm -rf /tmp/.X*-unix /tmp/.font-unix
+-
+-# Clean ICE locks
+-mkdir -p /tmp/.ICE-unix
+-chown root:root /tmp/.ICE-unix
+-rm -rf /tmp/.ICE-unix/*
+-chmod a+rwx,+t /tmp/.ICE-unix
++rm -rf /tmp/hsperfdata_* /tmp/mc-*
+ 
+ # Delete Postgres sockets
+ rm -f /tmp/.s.PGSQL.*
+ 
+-# GNOME and KDE related cleanup
+-rm -rf /tmp/.fam_socket /tmp/kde-* /tmp/ksocket-* /tmp/mcop-* /tmp/orbit-* /tmp/.esd /tmp/.sawfish-* /tmp/esrv* /tmp/kio* /tmp/scrollkeeper-tempfile.*
+-
+-# clean dynamic stuff
+-for f in /var/lib/gnome/desktop/dynamic_*.desktop /usr/share/apps/kdesktop/Desktop/dynamic_*.desktop; do
+-    if [ -r $f ]; then
+-	device=`sed -n 's/# dynamic_device=//p' $f`
+-	if [ -n "$device" -a ! -e "$device" ]; then
+-	    rm -f $f
+-	fi
+-    fi
+-done
+-
+ # openssh related cleanup
+ rm -rf /tmp/ssh-*
+ 
+@@ -1261,21 +1039,11 @@
  fi
  
  if [ -f /var/lock/TMP_1ST ];then
@@ -370,71 +645,6 @@
 -        [ -r "/etc/X11/$i.$XFree" ] && ln -sf "$i.$XFree" "/etc/X11/$i"
 -    fi
 -done
---- rc.d/rc.local.annvix	2005-02-28 15:42:51.000000000 -0700
-+++ rc.d/rc.local	2005-02-28 15:48:06.000000000 -0700
-@@ -5,23 +5,15 @@
- # want to do the full Sys V style init stuff.
- 
- [ -f /etc/sysconfig/system ] && source /etc/sysconfig/system
--[ -f /etc/sysconfig/msec ] && source /etc/sysconfig/msec
--[ -z "$SECURE_LEVEL" ] && SECURE_LEVEL=3
- [ -f /etc/sysconfig/init ] && source /etc/sysconfig/init
--if [ $SECURE_LEVEL -lt 4 ]; then
--    [ -z "$REWRITEISSUE" ] && REWRITEISSUE=rewrite
--    if [ $SECURE_LEVEL -lt 3 ]; then
--	[ -z "$REWRITEISSUENET" ] && REWRITEISSUENET=rewrite
--    fi
--fi
- 
--SYSTEM=${SYSTEM=Mandrakelinux}
-+SYSTEM=${SYSTEM=Annvix}
- 
- # Source functions
- . /etc/init.d/functions
- 
--if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/mandrake-release ]; then
--    R=$(cat /etc/mandrake-release)
-+if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/annvix-release ]; then
-+    R=$(cat /etc/annvix-release)
- 
-     arch=$(uname -m)
-     a="a"
-@@ -45,12 +37,7 @@
-     # This will overwrite /etc/issue at every boot.  So, make any changes you
-     # want to make to /etc/issue here or you will lose them when you reboot.
- 
--    if [ -x /usr/bin/linux_logo ]; then
--	/usr/bin/linux_logo -n -f | sed -e 's|\\|\\\\|g' > /etc/issue
--	echo "" >> /etc/issue
--    else
--	> /etc/issue
--    fi
-+    > /etc/issue
-     echo "$R" >> /etc/issue
-     echo "Kernel $(uname -r) on $a $SMP$(uname -m) / \l" >> /etc/issue
-     
-@@ -63,21 +50,6 @@
- 	gprintf "Welcome to %s\n" "$NAME" > /etc/issue.net
- 	echo "-------------------------" >> /etc/issue.net
-     fi
--else
--    if [ -f /etc/security/msec/issue.$SECURE_LEVEL ]; then
--	cat /etc/security/msec/issue.$SECURE_LEVEL > /etc/issue
--    elif [ -f /etc/security/msec/issue ]; then
--	cat /etc/security/msec/issue > /etc/issue
--    else
--	rm -f /etc/issue
--    fi
--    if [ -f /etc/security/msec/issue.net.$SECURE_LEVEL ]; then
--	cat /etc/security/msec/issue.net.$SECURE_LEVEL > /etc/issue.net
--    elif [ -f /etc/security/msec/issue.net ]; then
--	cat /etc/security/msec/issue.net > /etc/issue.net
--    else
--	rm -f /etc/issue.net
--    fi
- fi
- 
- touch /var/lock/subsys/local
 --- mandrake/usb.annvix	2005-03-01 13:16:48.000000000 -0700
 +++ mandrake/usb	2005-03-01 13:16:48.000000000 -0700
 @@ -103,47 +103,44 @@
@@ -532,3 +742,68 @@
 -VISOR=no
 -PRINTER=no
 \ No newline at end of file
+--- mandrake/tmpdir.sh.avx	2005-09-11 17:32:24.000000000 -0400
++++ mandrake/tmpdir.sh	2005-09-11 17:32:24.000000000 -0400
+@@ -6,20 +6,14 @@
+     . /etc/sysconfig/system
+ fi
+ 
+-if [ -f /etc/sysconfig/msec ];then
+-    eval `grep ^SECURE_LEVEL= /etc/sysconfig/msec | head -1`
+-fi
+-
+-if [[ "$SECURE_TMP" = "yes" || "$SECURE_TMP" = "1" || "$SECURE_TMP" = "YES" || "$SECURE_LEVEL" -ge 2 ]];then
+-    if [ -d ${HOME}/tmp -a -w ${HOME}/tmp ];then
+-	export TMPDIR=${HOME}/tmp
+-	export TMP=${HOME}/tmp
+-    elif mkdir -p ${HOME}/tmp >/dev/null 2>&1;then
+-	chmod 700 ${HOME}/tmp
+-	export TMPDIR=${HOME}/tmp
+-	export TMP=${HOME}/tmp
+-    else
+-	export TMPDIR=/tmp/
+-	export TMP=/tmp/
+-    fi
++if [ -d ${HOME}/tmp -a -w ${HOME}/tmp ];then
++    export TMPDIR=${HOME}/tmp
++    export TMP=${HOME}/tmp
++elif mkdir -p ${HOME}/tmp >/dev/null 2>&1;then
++    chmod 700 ${HOME}/tmp
++    export TMPDIR=${HOME}/tmp
++    export TMP=${HOME}/tmp
++else
++    export TMPDIR=/tmp/
++    export TMP=/tmp/
+ fi
+--- sysconfig/network-scripts/ifup.avx	2005-09-11 17:54:33.000000000 -0400
++++ sysconfig/network-scripts/ifup	2005-09-11 17:55:35.000000000 -0400
+@@ -202,13 +202,6 @@
+     fi
+ fi
+ 
+-# is the device wireless? If so, configure wireless device specifics
+-IS_WIRELESS=
+-if is_wireless_device ${DEVICE}; then
+-    . ./ifup-wireless
+-    IS_WIRELESS=1
+-fi
+-
+ # slave device?
+ if [ "${SLAVE}" = yes -a "${ISALIAS}" = no -a "${MASTER}" != "" -a \
+      -x /sbin/ifenslave ]; then
+--- sysconfig/network-scripts/network-functions.avx	2005-09-11 17:55:54.000000000 -0400
++++ sysconfig/network-scripts/network-functions	2005-09-11 17:56:06.000000000 -0400
+@@ -337,13 +337,6 @@
+     fi
+ }
+ 
+-is_wireless_device ()
+-{
+-    [ -x /sbin/iwconfig ] || return 1
+-    LC_ALL=C iwconfig $1 2>&1 | grep -q "no wireless extensions" || return 0
+-    return 1
+-}
+-
+ # Mainframe devices:
+ configure_ccwgroup_device ()
+ {
