- 2.6.22.15; fixes CVE-2007-5966, CVE-2007-6417 - ZZ01: patch to fix CVE-2007-6206 - make only the virtual kernel provide 'linux' - parallelize xargs invocations for smp machines (herton) - update scripts/apply_patches from Mandriva (v0.4):   - really use the series file now, taking the patches in their order   - fix usage output   - make sure no patches are forgotten in the patches directory; if a     patch isn't listed in series, exit with an error
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@8354 f191e5f7-4e04-0410-925a-985e7dbff663

diff --git a/releases/2.1-CURRENT/kernel26/SOURCES/patches/scripts/apply_patches b/releases/2.1-CURRENT/kernel26/SOURCES/patches/scripts/apply_patches
--- a/releases/2.1-CURRENT/kernel26/SOURCES/patches/scripts/apply_patches
+++ b/releases/2.1-CURRENT/kernel26/SOURCES/patches/scripts/apply_patches
@@ -1,18 +1,19 @@
 #!/bin/sh
-# Copyright (C) 2002 by MandrakeSoft,
-# Juan Quintela <quintela@mandrakesoft.com>, 
-# Redistribution of this file is permitted under the terms of the GNU 
+# Copyright (C) 2002,2007 by Mandriva,
+# Juan Quintela,
+# Herton Ronaldo Krzesinski <herton@mandriva.com>,
+# Redistribution of this file is permitted under the terms of the GNU
 # Public License (GPL)
 
-# This scripts applies all the *.patch & *.tar.* in order
+# This scripts applies all patches and 3rparty additions
 
-VERSION=0.3
+VERSION=0.4
 
 usage () {
-    echo "usage: `basename $0` [--version] [--start <number>]"
-    echo "             [-v] --patch_dir=<patch-dir>" >&2
-    echo -e "\t(ex: `basename $0`" >&2
-    exit 1
+	echo "usage: `basename $0` [--version] [--start <patch name>]" >&2
+	echo "                     [--stop <patch name>] [-v,--verbose]" >&2
+	echo "                     [--keep_origs] [--patch_dir=<patch-dir>]" >&2
+	exit 1
 }
 
 # Globals
@@ -29,32 +30,35 @@ print () {
 	echo -e "$1"
 }
 
+error () {
+	echo -e "$1" >&2
+	exit $2
+}
+
 # looking for options
 
 while [ $# -gt 0 ]; do
 	case $1 in
 		-v|--verborse)
 			verbose=1
-		    	;;
+			;;
 		--keep_origs)
 			keep_origs=1
 			;;
-	        --start=*)
-		        start_at="`echo $1 | sed -e 's/--start=//'`"
-			start_at="`echo $start_at | cut -f1 -d'_'| tr A-Z a-z`"
+		--start=*)
+			start_at="`echo $1 | sed -e 's/--start=//'`"
 			;;
-	        --stop=*)
-		        stop_at=`echo $1 | sed -e 's/--stop=//'`
-			stop_at="`echo $stop_at | cut -f1 -d'_'| tr A-Z a-z`"
+		--stop=*)
+			stop_at=`echo $1 | sed -e 's/--stop=//'`
 			;;
 		--version)
 			echo "`basename $0`: version $VERSION"
 			exit 0
 			;;
-	        --patch_dir=*)
-		        patch_dir=`echo $1 | sed -e 's/--patch_dir=//'`
+		--patch_dir=*)
+			patch_dir=`echo $1 | sed -e 's/--patch_dir=//'`
 			;;
-	        *)
+		*)
 			usage
 			;;
 	esac
@@ -66,78 +70,77 @@ if [ -z "$patch_dir" ]; then
 fi
 
 if [ ! -d "$patch_dir" ]; then
-	echo "$patch_dir is not a directory"
-	exit 2
+	error "$patch_dir is not a directory" 2
 fi
 
 print "patches dir is: $patch_dir"
 
-patches_names=./patches_names
+third_party="$patch_dir/3rdparty.series"
+patch_series="$patch_dir/series"
 
-# .sh can't be compressed
+# verify the integrity of patch dir, all patches must be listed in
+# series file and all third party additions on 3rdparty.series file
+files=""
+pushd "$patch_dir" >/dev/null
+	for file in *; do
+		[ "$file" != "3rdparty.series" -a "$file" != "series" ] \
+			|| continue
+		if echo $file | grep -q ".tar$"; then
+			! grep -q "$file" "$third_party" 2>/dev/null || \
+				files="$files $file"
+			continue
+		fi
+		if echo $file | grep -q ".patch$"; then
+			! grep -q "$file" "$patch_series" 2>/dev/null || \
+				files="$files $file"
+			continue
+		fi
+		files="$files $file"
+	done
+popd >/dev/null
+if [ -n "$files" ]; then
+	echo -n "Error, unrecognized or missing file(s) from " >&2
+	echo    "3rdparty.series/series files:" >&2
+	for file in $files; do
+		echo $file >&2
+	done
+	exit 3
+fi
 
-find $patch_dir -regex ".*\.\(patch\|tar\)\(\|\.bz2\|\.gz\)" -o -regex ".*\.sh" | \
-	sed 's/\.\(gz\|bz2\)$//' | \
-	sort -u > $patches_names
+# install third party additions; we separate 3rdparty from main patch
+# series because we can use then series file with quilt
+if [ -f "$third_party" ]; then
+	for file in `cat "$third_party" | grep -v "^[[:space:]]*#.*"`; do
+		print "processing $file"
+		tar -xf "$patch_dir/$file" \
+			|| error "failed to extract '$patch_dir/$file'" 4
+	done
+fi
 
-for file in `cat $patches_names` ; do
-	print "processing $file"
-	if [ -r "$file" ]; then
-		prog="cat"
-		name="$file"
-		option=""
-	elif [ -r "$file.gz" ]; then
-		prog="zcat"
-		option="z"
-		name="$file.gz"
-	elif [ -r "$file.bz2" ]; then
-		prog="bzcat"
-		name="$file.bz2"				
-		option="j"
-	else
-		echo "imposible to apply $file patch or tarball"
-		exit 3;
-	fi
-	number="`basename $file | cut -f1 -d'_'| tr A-Z a-z`"
-
-	if [[ "$number" < "$start_at" ]]; then
-		continue
-	elif [[ "$number" == "$start_at" ]]; then
-		start_at=""
-	fi
-
-	if [[ "$number" == "$stop_at" ]]; then
-		exit 4
-	fi
-
-	case $file in
-		*.patch)
-			suffix=".${number}.orig"
-			options="--version-control=simple --suffix=$suffix"
-			print "$prog $name | patch -sp1 $options"
-			$prog $name | patch -sp1 $options 
-			if [ "$?" != "0" ]; then
-				echo "patch `basename $name` failed"
-				exit 1
+# patches
+if [ -f "$patch_series" ]; then
+	[ "$verbose" -ne 0 ] && silent="" || silent="-s"
+	for file in `cat "$patch_series" | grep -v "^[[:space:]]*#.*"`; do
+		if [ -n "$start_at" ]; then
+			if [ "$file" != "$start_at" ]; then
+				continue
+			else
+				print "started at $file"
+				unset start_at
 			fi
-			;;
-		*.tar)
-			print "tar $option -xf$option $name"
-			tar -xf$option $name
-			;;
-		*.sh)
-			print "sh $name"
-			/bin/sh $name
-			;;
-		*)
-			print "unrecognized $file"
-			exit 0
-			;;
-	esac
-done
+		fi
+		if [ -n "$stop_at" ]; then
+			if [ "$file" == "$stop_at" ]; then
+				print "stopped at $file"
+				break
+			fi
+		fi
+		print "processing $file"
+		patch -p1 $silent -b -z .`basename $file .patch`.orig < "$patch_dir/$file"
+		[ "$?" -eq 0 ] || error "patch $file failed" 5
+	done
+fi
 
 [[ $keep_origs -eq 0 ]] && find . -name "*.orig" | xargs rm -f
-
-rm $patches_names
 
 exit 0
